const maps = {
    Originalkart: {
        territories: [
            'Alaska',
            'Nordvest-territoriet',
            'Grønland',
            'Alberta',
            'Ontario',
            'Quebec',
            'Vest-Amerika',
            'Øst-Amerika',
            'Mellom-Amerika',
            'Venezuela',
            'Peru',
            'Brasil',
            'Argentina',
            'Island',
            'Skandinavia',
            'Ukraina',
            'Storbritannia',
            'Nord-Europa',
            'Vest-Europa',
            'Sør-Europa',
            'Nord-Afrika',
            'Egypt',
            'Kongo',
            'Øst-Afrika',
            'Sør-Afrika',
            'Madagaskar',
            'Midtøsten',
            'Afghanistan',
            'Ural',
            'Sibir',
            'Jakutsk',
            'Irkutsk',
            'Kamsjaktka',
            'Japan',
            'Mongolia',
            'Kina',
            'India',
            'Siam',
            'Indonesia',
            'Ny-Guinea',
            'Vest-Australia',
            'Øst-Australia'
        ],

        missions: [
            '<p>Du må eliminere alle de GRØNNE BATALJONENE</p> <p>Hvis du selv kontrollerer de grønne bataljonene eller de allerede er blitt eliminert av en annen spiller er ditt oppdrag:</p> <p>Du skal KONTROLLERE 24 OMRÅDER.</p>',
            '<p>Du må eliminere alle de FIOLETTE BATALJONENE</p> <p>Hvis du selv kontrollerer de fiolette bataljonene eller de allerede er blitt eliminert av en annen spiller er ditt oppdrag:</p> <p>Du skal KONTROLLERE 24 OMRÅDER.</p>',
            '<p>Du må eliminere alle de GULE BATALJONENE</p> <p>Hvis du selv kontrollerer de gule bataljonene eller de allerede er blitt eliminert av en annen spiller er ditt oppdrag:</p> <p>Du skal KONTROLLERE 24 OMRÅDER.</p>',
            '<p>Du må eliminere alle de SVARTE BATALJONENE</p> <p>Hvis du selv kontrollerer de svarte bataljonene eller de allerede er blitt eliminert av en annen spiller er ditt oppdrag:</p> <p>Du skal KONTROLLERE 24 OMRÅDER.</p>',
            '<p>Du må eliminere alle de BLÅ BATALJONENE</p> <p>Hvis du selv kontrollerer de blå bataljonene eller de allerede er blitt eliminert av en annen spiller er ditt oppdrag:</p> <p>Du skal KONTROLLERE 24 OMRÅDER.</p>',
            '<p>Du må eliminere alle de RØDE BATALJONENE</p> <p>Hvis du selv kontrollerer de røde bataljonene eller de allerede er blitt eliminert av en annen spiller er ditt oppdrag:</p> <p>Du skal KONTROLLERE 24 OMRÅDER.</p>',
            '<p>Du skal erobre EUROPA og SYD-AMERIKA og et tredje kontinent som du velger selv.</p>',
            '<p>Du skal erobre ASIA og AFRIKA</p>',
            '<p>Du må erobre hele ASIA og SYD-AMERIKA</p>',
            '<p>Du skal erobre 24 OMRÅDER hvor som helst på brettet.</p>',
            '<p>Du skal erobre 18 OMRÅDER etter fritt valg og ha minst to bataljoner i hvert område.</p>',
            '<p>Du skal erobre NORD-AMERIKA og AFRIKA</p>',
            '<p>Du må erobre kontinentene EUROPA og AUSTRALIA pluss et valgfritt kontinent.</p>',
            '<p>Du skal erobre NORD-AMERIKA og AUSTRALIA</p>'
        ]
    },


    Nordeuropakart: {
        territories: [
            'Vestlandet',
            'Innlandet',
            'Akershus',
            'Telemark',
            'Sørlandet',
            'Dalarna',
            'Värmland',
            'Stockholm',
            'Västergötaland',
            'Östergötaland',
            'Kalmar',
            'Skåne',
            'Nord-Jylland',
            'Sør-Jylland',
            'Fyn og Sjælland',
            'Irland',
            'Nord-Irland',
            'Skottland',
            'Wales',
            'Nord-England',
            'Sentral-England',
            'Sør-England',
            'Normandie',
            'Champagne',
            'Paris',
            'Alsace-Lorraine',
            'Aquitaine',
            'Rhône-Alpes',
            'Rivieraen',
            'Belgia',
            'Nederland',
            'Luxembourg',
            'Vest-Pommern',
            'Niedersachsen',
            'Brandenburg',
            'Vestfalen',
            'Baden-Württemberg',
            'Bayern',
            'Sveits',
            'Tirol',
            'Piemonte',
            'Lombardia',
            'Veneto',
            'Øst-Pommern',
            'Mazovia',
            'Stor-Polen',
            'Lesser-Polen',
            'Bohemia',
            'Moravia',
            'Slovakia',
            'Østerrike',
            'Slovenia',
            'Transdanubia',
            'Puszta'
        ],

        missions: [
            'Utslett gul',
            'Utslett rød',
            'Utslett blå',
            'Utslett grønn',
            'Utslett lilla',
            'Utslett svart'
        ]
    },
    

    Badaboom: {
        territories: [
            'Jigglistan',
            'Stanistan',
            'Yen-stan',
            'Bi-stan',
            'Ging',
            'Gang',
            'Gollie',
            'Watcha',
            'Gå',
            'Heyla',
            'Sheila',
            'Shallie',
            'Wallei',
            'Ompa',
            'Epshe',
            'Acus',
            'Corina',
            'Gnossos',
            'Apoleis',
            'Raak',
            'Ur-kha',
            'Mahr',
            'Akuun',
            'Asaan',
            'Khagan',
            'Kour Rach',
            'Tyh',
            'Jah',
            'Dah',
            'Brah',
            'Tsjh',
            'Hymn',
            'Lyra',
            'Tûbah',
            'Bossa',
            'Nova',
            'Nökiir',
            'Voss Kilda',
            'Sperasska',
            'Tüngsten',
            'Voss Dür'
        ],

        missions: [
            'Utslett gul',
            'Utslett rød',
            'Utslett blå',
            'Utslett grønn',
            'Utslett lilla',
            'Utslett svart'
        ]
    },
    
    Trondheim: {
        territories: [
            'Ila',
            'Kalvskinnet',
            'Pirbadet',
            'Sentrum',
            'Nidarosdomen',
            'Marienborg',
            'Sverresborg',
            'Havsten',
            'Ugla',
            'Byåsen',
            'Selsbakk',
            'Munkvoll',
            'Hallset',
            'Øya',
            'Studentersamfundet',
            'Elgeseter',
            'Gløshaugen',
            'Lerkendal',
            'Nardo',
            'Berg',
            'Moholt',
            'Sorgenfri',
            'Nidarvoll',
            'Othilienborg',
            'Nedre Steinan',
            'Sluppen',
            'Stubban',
            'Lade',
            'Østmarka',
            'Ringve',
            'Møllenberg',
            'Strindheim',
            'Bakklandet',
            'Festningen',
            'Persaunet',
            'Singsaker',
            'Tyholt',
            'Brundalen',
            'Strinda',
            'Dragvoll',
            'Steinan'
        ],

        missions: [
            'Utslett gul',
            'Utslett rød',
            'Utslett blå',
            'Utslett grønn',
            'Utslett lilla',
            'Utslett svart'
        ]
    }
};

exports.maps = maps;